### ISSUE TITLE
Undefined method issue 

### ISSUE THREAD

**Issue by Austinate** [orta/chairs#11]
doing `chairs pull anyname`

Gives me such output in terminal: 

```
/Users/austinate/.rvm/gems/ruby-2.2.1/gems/chairs-1.1.0/lib/musician.rb:254:in `get_app_name': undefined method `each' for #<Pow::Base:0x007ffe951afb30> (NoMethodError)
    from /Users/austinate/.rvm/gems/ruby-2.2.1/gems/chairs-1.1.0/lib/musician.rb:188:in `setup'
    from /Users/austinate/.rvm/gems/ruby-2.2.1/gems/chairs-1.1.0/lib/musician.rb:46:in `pull'
    from /Users/austinate/.rvm/gems/ruby-2.2.1/gems/chairs-1.1.0/lib/musician.rb:17:in `initialize'
    from /Users/austinate/.rvm/gems/ruby-2.2.1/gems/chairs-1.1.0/bin/chairs:8:in `new'
    from /Users/austinate/.rvm/gems/ruby-2.2.1/gems/chairs-1.1.0/bin/chairs:8:in `<top (required)>'
    from /Users/austinate/.rvm/gems/ruby-2.2.1/bin/chairs:23:in `load'
    from /Users/austinate/.rvm/gems/ruby-2.2.1/bin/chairs:23:in `<main>'
    from /Users/austinate/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
    from /Users/austinate/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

Had a try to google possible fix, but failed. 
Looks like probably wrong Ruby version is used? But i'm not sure which one do i need to use. Thanks for help :)

**Comment by kevboh** [comment]
+1. Also just got this.

**Comment by jcampbell05** [comment]
Unfortunately I am getting this too for Ruby 2.1.5 @orta

**Comment by orta** [comment]
ah, yeah, I've not really been using Chairs for the last year or so, probably best that someone takes over and updates it. Ideally a lot of the stuff `pow` does can be replaces with `Pathname` now.

**Comment by netbe** [comment]
+1
@orta do you know other similar tools to view the simulator data?

**Comment by orta** [comment]
Aye, Simpholder is a Mac app that does it - https://simpholders.com
